version: '3.1'

services:
  db:
    container_name: mysql-db
    image: mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}